### PR TITLE
Updated simple-example.md

### PR DESCRIPTION
**Pull request by divyenduz**
Move to the updated link on howtographql.com as learnapollo.com is deprecated. Please let me know if I need to change the label as well or if this is not relevant.

### CODE REVIEW

**Comment by stubailo** [comment]
Yes - please change that to "How to GraphQL" since it's no longer called learn Apollo. Thanks!

**Comment by divyenduz** [comment]
I have changed the label to "How to GraphQL". Please let me know if anything else needs to be done for this? Thanks!

**Comment by stubailo** [comment]
That's perfect, thanks!

**Comment by stubailo** [comment]
Could you update this page as well? http://dev.apollodata.com/react/

**Comment by divyenduz** [comment]
Done via https://github.com/apollographql/react-docs/pull/282

Please let me know if any changes are needed. Thanks.

**Comment by stubailo** [comment]
thanks!

**Pull request merged**
