### PR TITLE
Fixed faulty import for IntrospectionFragmentMatcher

### PR DESCRIPTION
**Pull request by timbrandin**

### CODE REVIEW

**Comment by stubailo** [comment]
`react-apollo` in recent versions re-exports everything from `apollo-client`, so this should actually work. Doesn't it? What versions are you using?

**Comment by timbrandin** [comment]
Oh, I see, maybe we're not using the latest version then. We're on 0.13.3 of react-apollo and 1.3.0 of apollo-client.

**Comment by stubailo** [comment]
Yeah, `react-apollo` is at `1.4.1` now - might be worth looking at upgrading!

**Comment by stubailo** [comment]
Since we don't currently do documentation versioning, I'm going to close this. Probably around a 2.0 release we should start versioning docs.

**Pull request closed without merging**
