### PR TITLE
Adds a minimal mention of Direct Cache Access

### PR DESCRIPTION
**Pull request by Siyfion**
And links to the relevant bit in the Vanilla JS section.

### CODE REVIEW

**Comment by helfer** [comment]
Thanks for the PR @Siyfion! Can you make the example a full one that includes decorating a component with `graphql` and then using the `mutate` function inside of it? That would be awesome!

**Comment by stubailo** [comment]
I think this is actually the best documentation to link to maybe? http://dev.apollodata.com/react/api-mutations.html#graphql-mutation-options-update

**Comment by Siyfion** [comment]
@stubailo & @helfer I've changed the link to the one Sashko posted and I've fleshed out the example a bit more. I can expand it even more, but I didn't want to write an _enormous_ example in comparison to the others on the page, as it might be a bit overkill? Thoughts please!

**Comment by stubailo** [comment]
This is great, thanks!

**Comment by Siyfion** [comment]
Always happy to help. 👍

**Pull request merged**
